prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong

src/App.tsx
landing 페이지는 Header와 Footer를 사용하는 유형의 페이지가 아닌데 App.tsx에서 Layout을 사용하는 페이지로 라우팅되고 있습니다.
그래서 반대로 Layout을 사용하면서 라우팅 등록이 필요한 Meditation 페이지를 Landing 대신 라우팅 처리하도록 변경하였습니다.
(생략)
개발환경에서 잘 적용되는 것을 확인했는데 혹시 놓치고 있는 부분이 있으면 알려주세요~
(없으면 LGTM👍)
=> 🚨Fix: Landing 페이지 Route 수정

src/pages/landing/index.tsx, src/pages/landing/style.tsx, src/pages/signup/index.tsx
1. 반응형 페이지로 스타일 수정했습니다
2. 스타일과 컴포넌트 파일을 분리했습니다
=> 💄 landingPage/UI 스타일 수정

src/pages/landing/index.tsx, src/pages/layout/index.tsx, src/pages/login/components/GoToSignUp.tsx, src/pages/login/index.tsx, src/pages/meditation/components/MeditaionCounter.tsx, src/pages/profile/components/ProfileInfo/index.tsx, src/pages/signup/index.tsx
=> 📝 Chore: 공통 컴포넌트 import 수정

index.html
warning 메세지가 나서
`./public/assets/favicon.ico` 에서 `/assets/favicon.ico` 로 수정 했습니다.
=> 📝 Chore: 파비콘 경로 수정

src/components/PostPreview/PostHeader.tsx
모듈 내보내기 컨벤션으로 바꿈으로써 import 경로에 난 오류를 수정하였습니다.
=> 🚨 Fix: post/PostPreview Icon import 경로 수정

src/components/UserInput/UserInput.style.ts, src/pages/profile/Profile.tsx, src/pages/signup/constants/index.ts, src/pages/signup/validations/index.ts
비밀번호는 8자 이상 32자 이하여야 하며
영문자 숫자 특수기호 중 두개이상 포함해야 하게 수정했습니다.
=> 🚨 Fix: signup validation 수정

src/apis/posting/index.ts, src/pages/posting/components/NewPost.tsx, src/pages/posting/components/PassPosting.tsx, src/pages/posting/utils/createFormData.ts, src/pages/posting/utils/index.ts
바보같이... push 를 안하고 merge 를 시켰습니다...
try-catch, promise 를 사용하여 API 비동기처리를 했습니다.
추후 util 함수에 관한 것만 따로 보완할 예정입니다
이후 업데이트할 ui 를 위해 남겨두었습니다
=> 🔨 post/Posting PR 리뷰 반영

src/App.tsx, src/pages/setting/Setting.style.ts, src/pages/setting/Setting.tsx, src/pages/setting/index.ts
셋팅 페이지 UI 구현했습니다.
setting page라서 /setting으로 경로 설정했습니다.
=> ✨ Setting/UI 구현

src/components/Footer/Footer.tsx
- 푸터의 프로필 페이지로 이동하는 링크 속성을 수정했습니다
- token이 유효하지 않으면 로그인 페이지로 이동하는 기능 또한 포함돼있습니다
(생략)
(생략)
=> 🚨 Fix: Footer Profile 페이지 링크 수정

src/App.tsx, src/apis/user/index.ts, src/components/Avatar/Avatar.tsx, src/components/Footer/Footer.tsx, src/hooks/useSessionStorage.ts, src/pages/login/index.tsx, src/pages/profile/components/ProfileEdit/ProfileEdit.tsx, src/pages/signup/index.tsx, src/utils/PrivateRoute.tsx
1. useSessionStorage 추가
2. 로그인시 세션 스토리지에 id, tokeb값 추가
3. 리다이렉트 storage에서 값 가져와서 판단
4. 푸터 프로필 클릭할때 storage에서 id 가져옴
5. 닉네임 변경 api요청 토큰 값 스토리지에서 가져옴
결국 토큰 값을 쓸 때 'Bearer' 앞에 붙여야 하는데 언제 Bearer를 붙여주는게 좋을까요? 지금은 api요청할 때 붙여줍니다
다른 분들이 제작한 부분을 건드려야 했는데 최소한으로 건드렸습니다.
=> ✨Feat : sessionStorage에 _id, token 값 저장

src/pages/profile/components/FollowButton/FollowButton.tsx, src/pages/profile/components/FollowUser/FollowUser.tsx
1. followButton의 재사용을 위해 분리하였습니다.
=> ✨ Feat:	Profile/followButton 

src/pages/password-update/PasswordUpdate.tsx
토큰이 있으면 profile 페이지로 이동
토큰이 없으면 login 페이지로 이동
=> 🚨Fix: 비밀번호 재설정 완료 후 라우팅 주소 변경

src/pages/landing/Landing.style.tsx
스타일 오차 수정 했습니다.
스크롤 사라졌는데 혹시 생긴다면 알려주세요~
=> 💄 Style: Landing/UI

src/styles/emotion.d.ts
- 이제 themeProvider에서 제공하는 color와 style에 대한 타입 추론이 가능합니다
thanks to @sgd122 🙇‍♂️
=> 🔨 Refactor: themeProvider 타입 추론 가능

src/components/Link/Link.style.ts, src/components/PostPreview/PostHeader.tsx, src/components/PostPreview/PostPreview.style.ts, src/components/PostPreview/PostPreview.tsx, src/routes/PageRoutes.tsx
- posts 페이지에 맞춰 링크 컴포넌트 스타일을 변경했던 것을 다시 돌려놓았습니다.
- posts 에 추가 스타일을 입혀 스타일을 정렬했습니다.
- Header, Footer Layout 이 보이지 않는 곳에 Route 를 배치한 문제를 수정했습니다.
생략합니다.
=> 🚨 Fix: link 컴포넌트 스타일 수정

src/components/ThemePicker/ThemePicker.tsx, src/pages/posting/components/NewPost/NewPost.tsx
- merge 시 충돌 해결했습니다.
- handleThemeClick 을 선택 prop 으로 바꾸었습니다.
생략합니다.
창기님 나연님 늦은 시간까지 고생이 많으세요
=> 🚨Fix: NewPost merge 충돌 해결

src/pages/meditation/components/MeditationTimeSetter.style.ts, src/pages/meditation/components/MeditationTimeSetter.tsx
- 이제 명상 시간을 사용자가 입력해서 설정할 수 있습니다!
- TimeSetter의 버튼을 길게 누르면 마우스가 여러번 클릭된 것처럼 빠르게 시간이 변화합니다! (모바일 터치 대응 완료)
연타 기능(이하 longclick)을 훅으로 빼는게 더 나았을까요?
=> ✨ Feat: TimeSetter 업그레이드

src/components/PostPreview/PostHeader.tsx
잘못된 image src 을 넘겨주고 있던 문제를 수정했습니다.
생략합니다.
=> 🚨 Fix: 사용자 프로필이 출력되지 않는 문제 수정

src/routes/PageRoutes.tsx, src/routes/PublicRoute.tsx, src/routes/utils/checkAuth.ts
Public 라우터 추가 했습니다. 이제 로그인이 된 경우 로그인, 랜딩페이지, 회원가입 페이지로 들어가면 posts 페이지로 리다이렉트 됩니다.
=> ✨Feat : public 라우터 추가

src/pages/password-update/PasswordUpdate.tsx
비밀번호 재설정에 Footer가 두개 존재하는 오류 수정했습니다.
비밀번호 재설정에 비밀번호 유효성 검사 수정했습니다.
생략합니다.
=> 🚨 Fix: password update UI오류 수정, 유효성 검사 수정

src/pages/posting/Posting.tsx
아래 오류 사항을 해결했습니다.
useNavigate 를 선언하지 않고 navigate Function 을 호출한 문제를 수정했습니다. (merge 문제)
posting 페이지로 임의로 접근할 시 구조분해 할당이 안되는 문제를 수정하면서 를NewPost 에 잘못된 prop 을 넘겨주는 문제를 수정했습니다.
생략합니다.
생략합니다.
=> 🚨 Fix: validation 프로퍼티 넘겨주지 않은 문제 수정

src/components/PostPreview/PostHeader.tsx, src/components/Toast/Toast.style.ts, src/components/Toast/Toast.tsx, src/pages/posting/components/NewPost/NewPost.style.ts, src/pages/posting/components/NewPost/NewPost.tsx, src/pages/posting/constants/index.ts
- 글자수가 많아지면 버튼이 글자를 가리던 문제를 해결했습니다.
- 500자가 되면 글자 제한 알림을 보여줍니다.
자꾸 하나만 고쳐야 하는데...한꺼번에 고치게 되네요 자중하겠습니다
=> 🚨 Fix: Posting 글자가리는 문제 수정

src/pages/login/Login.style.tsx, src/pages/password-update/PasswordUpdate.style.ts, src/pages/signup/signup.style.ts, src/styles/global.tsx
- 페이지가 좌측 정렬되어 있던 스타일을 가운데 정렬로 수정했습니다.
=> 💄 Style: 페이지 전체 가운데 정렬 및 전체 페이지 너비 통일

src/pages/posting/components/SkipPosting/SkipPosting.tsx
- 건너뛰기 클릭 시 확인을 누르기도 전에 포스팅 발행 내용이 세션 스토리지에서 삭제되는 문제를 수정했습니다.
=> 🚨 Fix: 건너뛰기 클릭 문제

src/pages/NotFound/NotFound.tsx, src/pages/posting/Posting.style.ts, src/pages/posting/components/NewPost/NewPost.style.ts, src/pages/posting/components/SkipPosting/SkipPosting.style.ts
- Posting Page 에서 Posting UI 가 Footer 를 넘어오며 잘리던 문제를 수정하였습니다.
=> 💄 Style: height style 수정

src/pages/notice/Notice.style.ts, src/pages/notice/Notice.tsx, src/pages/notice/components/NoticeItem/NoticeItem.style.ts, src/pages/notice/components/NoticeItem/NoticeItem.tsx, src/pages/notice/constants/index.ts, src/pages/postDetail/components/PostCommentHeader.tsx, src/pages/postDetail/components/PostCommentInput.tsx
Comment 알림 생성
알림 읽음 처리 버튼 생성해서 처리
알림창 알림 아이템 사용자 아바타 수정
Like 알림 생성
=> 🚨Fix: 알림 생성, 알림창 수정

src/pages/layout/components/AlertButton.tsx
=> 🚨fix : 헤더 알람 비로그인시 에러 해결

src/components/Badge/DotBadge.style.ts, src/components/Badge/DotBadge.tsx, src/components/Button/Button.tsx, src/components/Button/Buttons.style.ts, src/components/Link/Link.tsx, src/components/ThemePicker/PickerNextButton.tsx, src/components/ThemePicker/PickerPreviousButton.tsx, src/pages/layout/components/SearchResultPost.tsx, src/pages/login/components/GoToSignUp.tsx, src/utils/index.ts
color값, 타입과 관련된 자잘한 오류들을 수정했습니다
(생략)
(생략)
=> 🚨 Fix: 배포 전 빌드 단계에서 발견한 오류 수정

src/components/Skeleton/SkeletonFollowUserInfo.style.ts, src/components/Skeleton/SkeletonFollowUserInfo.tsx, src/components/Skeleton/index.ts
FollowUserInfo Skeleton UI 를 구현했습니다.
생략
=> ✨ Feat: FollowUserInfo Skeleton UI 구현

src/pages/signup/constants/index.ts
=> 🚨Fix: SignUp 올바른 이메일 형식 메시지 수정

src/pages/password-update/PasswordUpdate.style.ts, src/pages/password-update/PasswordUpdate.tsx
=> 💄 Style:	비밀번호 재설정 페이지 로고 제거

src/apis/search/index.ts, src/components/PostPreview/PostPreview.tsx, src/pages/layout/components/AlertButton.tsx, src/pages/layout/components/SearchHead.tsx, src/pages/layout/components/SearchResultPost.tsx, src/pages/layout/types/index.ts, src/pages/layout/types/typeGuard.ts, src/pages/layout/utils/filterPostData.ts, src/types/Post.ts, src/types/index.ts
1. 헤더 submit 에러 해결
2. notice page에서의 header 알림 처리
=> 🚨Fix : header/alert and search

src/components/Footer/Footer.style.ts, src/components/Footer/index.ts
=> ✨ Feat: Footer/style 재생성

src/pages/meditation/components/MeditationTimer.style.ts, src/pages/meditation/components/MeditationTimer.tsx
- 이제 명상 시작 전을 제외하고 타이머 동작 중일 때 타이머 테두리가 회전합니다!
- 그리고 일시정지 시 멈춥니다!
thanks to @hyesung99 , @nayeon-hub
=> ✨ Feat: 타이머 상태에 따른 애니메이션 추가

src/components/Skeleton/PostPreviewSkeleton.style.ts, src/components/Skeleton/SearchFollowSkeleton.style.ts, src/components/Skeleton/SearchFollowSkeleton.tsx, src/components/Skeleton/SearchPostPreviewSkeleton.tsx, src/components/Skeleton/index.ts, src/components/Toast/Toast.style.ts, src/components/Toast/Toast.tsx, src/pages/layout/components/Footer.tsx, src/pages/layout/components/Header.tsx, src/pages/layout/components/IconNav.tsx, src/pages/layout/components/SearchBody.tsx, src/pages/layout/components/SearchNoResult.style.ts, src/pages/layout/components/SearchNoResult.tsx, src/pages/layout/components/SearchResultPost.tsx, src/pages/layout/components/SearchResultUser.tsx, src/pages/layout/components/index.ts, src/pages/layout/states/openSearch.ts
1. search 로딩 처리, 에러 처리 [5c25e23](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/pull/143/commits/5c25e2347f5b4dadc42e8250491d8b909cc73c26)
2. 검색 없음 표시 [b9ae4ca](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/pull/143/commits/b9ae4ca09307ed84c0917d379b27947ea3d04cd3)
3. 검색하다가 헤더 누르면 검색 창 사라지고 헤더 경로로 이동 [20edffd](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/pull/143/commits/20edffd1adf3a93dd19ca98ae1b5aba2238bd52e)
toast top props 받는 형태로 바꿨습니다 
검색에서도 toast가 상단에 위치기는 한데 헤더 아래에 검색 필터가 있다 보니 검색 필터 아래에 위치 시켰습니다
=> ✨Feat : Search/suspense

src/pages/notice/Notice.tsx, src/pages/notice/components/NoticeItem/NoticeItem.style.ts, src/pages/notice/components/NoticeItem/NoticeItem.tsx, src/pages/notice/utils/typeToIcon.ts
=> ✨Feat: notice/item

src/components/Skeleton/Skeleton.style.ts, src/pages/posting/components/SkeletonPosting/index.ts, src/pages/posts/components/SkeletonPosts/SkeletonPosts.style.ts, src/pages/posts/components/SkeletonPosts/SkeletonPosts.tsx, src/pages/posts/components/SkeletonPosts/index.ts, src/routes/PageRoutes.tsx
- Animation gradient 색상을 변경했습니다.
- Posting 페이지에 있던 스켈레톤 ui 를 Posts 페이지로 이동했습니다.
- 배경색상과 겹쳐 스켈레톤 ui 가 나타나지 않던 문제를 수정했습니다.
생략!
생략!
=> 💄 Style: Skeleton Style 변경

src/components/PostPreview/PostHeader.tsx, src/pages/layout/components/SearchBody.style.ts, src/pages/postDetail/components/PostContent.tsx
import문 누락 수정 + searchBody z-index 수정하였습니다!
=> 🚨 Fix: import문 누락 수정 + searchBody z-index 수정

src/routes/PageRoutes.tsx
- 페이지 네이밍 컨벤션에 맞게 소문자로 수정하였습니다.
죄송합니다...
=> 🔨 Refactoring: NotFound 페이지 이름 일관성있게 수정

src/components/Button/Button.tsx, src/components/Button/Buttons.style.ts, src/hooks/useDebounce.ts, src/pages/posting/Posting.tsx, src/pages/posting/components/NewPost/NewPost.tsx, src/pages/posting/components/NewPost/NewPostConfirm.tsx
- error 발생시 토스트가 보여져야 하는 컴포넌트가 사라졌던 걸 복원했습니다
- 구조분해한 변수를 사용해야하는 코드가 사라졌던걸 복원했습니다
useDebounce 에 의존성 배열이 재선언되어 무한 디바운싱 되는 문제를 수정했습니다
이제 발행 버튼을 한번 누르고 나면 발행 버튼이 disabled 처리가 됩니다! 
```tsx
{isError && (
<Toast
type={'ERROR'}
content='글을 발행할 수 없습니다. 잠시 후 다시 시도해주세요.'
/>
)}
```
```tsx
const { totalTime, channelLabel, channelId } = meditationInfo;
// react-query 내부부분
onSuccess: () => {
sessionStorage.removeItem('posting');
navigate('/posts', {
state: {
channelInfo: {
id: channelId,
label: channelLabel
}
}
});
}
```
```tsx
useEffect(() => {
run();
}, [...dependency, run]);
```
=> ✨, 🚨 Fix: posting 페이지 리팩토링
